import type { AgentPlan } from "@/agent/controller/types";

export function createMockPlan(
	steps: Array<{
		tool: string;
		params: Record<string, unknown>;
		description: string;
	}>,
	complexity: "simple" | "medium" | "complex" = "simple",
): AgentPlan {
	return {
		complexity,
		reasoning: "Test plan generated by mock",
		steps: steps.map((s, i) => ({
			...s,
			id: `step-${i}-${Date.now()}`,
			risk: "none" as const,
		})),
		needsConfirmation: false,
	};
}

export async function mockLLMResponse(
	page: import("@playwright/test").Page,
	plan: AgentPlan,
): Promise<void> {
	await page.route("**/api/agent/plan", async (route) => {
		await route.fulfill({
			status: 200,
			contentType: "application/json",
			body: JSON.stringify({ plan }),
		});
	});
}
